apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
# specs for the deployment
spec:
  replicas: 3
  # selector to identify the pods created by this deployment
  selector:
    matchLabels:
      component: web
  # template for the pods
  template:
    metadata:
    # labels and selector should match this is how the deployment identifies the pods it manages
      labels:
        component: web
    # specification for the pod (containers) that will be created by this deployment
    spec:
      containers:
      - name: client
        image: tcollins520/multi-client 
        ports:
        - containerPort: 3000
  
